name: 'Discord and Line notification'
description: 'Outputs a message to Discord and Line.'
author: bawonsak
branding:
  icon: message-square
  color: gray-dark
inputs:
  line:
    description: 'The boolean to check if Line should notify.'
    required: false
  discord:
    description: 'The boolean to check if Discord should notify.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
