name: DEV - Build

on:
  push:
    branches:
      - 'master'

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Discord notification
        uses: bawop443/action-discord@master
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1209721626833461298/lRVrZbxErWDZwRjxgGbsZEBYv85qqP67upasvZDhAU13ihVzZZuGiovezoEKWHJTK0f2
          DISCORD_USERNAME: MC - Deploy Notification
          DISCORD_AVATAR: https://cdn.discordapp.com/attachments/988683025942454312/1095604009252966482/image_1.png?ex=666fdebf&is=666e8d3f&hm=8a919283a14b81683dc7cc5a4aa61e5117fc8769f8ac85bcb4d4fe1f24263e61&
          GITHUB_JOB_STATUS: ${{ job.status }}
          